[manager]
linemode    = "size"
show_hidden = true


[opener]
image_viewer = [
	{ run = 'swayimg "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "image_viewer" }, 
]

